# Generated by Django 4.1.2 on 2022-12-18 11:53

import configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to=configuration.models.filepath)),
                ('lien', models.CharField(max_length=300, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200, null=True)),
                ('tache', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('mail', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=configuration.models.filepath)),
                ('poste', models.CharField(max_length=150)),
                ('linkdin', models.CharField(max_length=250, null=True)),
                ('behance', models.CharField(max_length=250, null=True)),
                ('git', models.CharField(max_length=250, null=True)),
                ('fb', models.CharField(max_length=250, null=True)),
                ('tel', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('tache', models.TextField()),
                ('date', models.DateField()),
                ('lien', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField(null=True)),
            ],
        ),
    ]
